apiVersion: v1
kind: ConfigMap
metadata:
 labels:
   app: ms-java-flynas-worker
   component: filebeat
 namespace: NamespaceName
 name: filebeat-sidecar-ms-java-flynas-worker
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        paths:
          - "/var/log/*.log"
        fields_under_root: true
        tags: ENVIRONMENT-flynas-worker
        multiline:
          pattern: '^\S.*[0-9]{1,4}-[0-9]{2}-[0-9]{2,4}'
          negate: true
          match: after
          max_lines: 500
        fields:
          type: ENVIRONMENT
          app_id: ENVIRONMENT-flynas-worker
    output:
      logstash:
        hosts: ["ELKHOST"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-java-flynas-worker 
  namespace: NamespaceName
  labels:
    app: ms-java-flynas-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable
  selector:
    matchLabels:
      app: ms-java-flynas-worker
  template:
    metadata:
      labels:
        app: ms-java-flynas-worker
    spec:
      containers:
      - name: ms-java-flynas-worker
        image: IMAGE_URL_WITH_TAG
        resources:
          requests:
            cpu: 50m
            memory: "128Mi"
          limits:
            cpu: 1000m
            memory: "1000Mi"
        ports:
        - containerPort: 8086
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 8086
            path: "/actuator/health"
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 20
          successThreshold: 2
          failureThreshold: 2
          timeoutSeconds: 2
        volumeMounts:
        - name: filebeat-logs
          mountPath: /var/log/
      - name: filebeat-sidecar
        image: docker.elastic.co/beats/filebeat:7.5.0
        volumeMounts:
        - name: filebeat-logs
          mountPath: /var/log/
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
      volumes:
        - name: filebeat-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-sidecar-ms-java-flynas-worker
            items:
              - key: filebeat.yml
                path: filebeat.yml
      imagePullSecrets:
      - name: my-secret-docker-pass


---
    apiVersion: v1
    kind: Service
    metadata:
      name: ms-java-flynas-worker-service
      namespace: NamespaceName
      labels:
        app: ms-java-flynas-worker
    spec:
      type: ClusterIP
      selector:
        app: ms-java-flynas-worker
      ports:
        - name: ms-java-flynas-worker-service
          port: 8086
          targetPort: 8086
      sessionAffinity: ClientIP
         
