name: Build Java Application
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: listing directory
        run: ls -l
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Run Dockerfile
        run: docker build --no-cache -f Infra/docker/Dockerfile -t  github-action:1
      - name: listing docker image
        run: docker images
